### PR TITLE
Added files for IMT2020065

### PR DESCRIPTION
**Pull request by Shridhar2602**

### CODE REVIEW

**Comment by Shridhar2602** [comment]
You guys will now merge this with main branch right? bcoz I can't see my profile yet.

**Comment by jaggu21** [comment]
@Shridhar2602 The changes will be reflected only after merging the PR.

**Comment by GaganAgarwal77** [comment]
@Shridhar2602 please change the date in the markdown file to , 2021-01-01 12:12:12 , And for the socials part you can put links to your instagram/facebook etc.

**Comment by Shridhar2602** [comment]
> @Shridhar2602 please change the date in the markdown file to , 2021-01-01 12:12:12 , And for the socials part you can put links to your instagram/facebook etc.

Ok Done !
https://github.com/zense/JuniorsGitTutorial/pull/18/commits/cbf53532e3060ebe1470ac9514d00649dc7b27cf

**Comment by GaganAgarwal77** [comment]
Well Done @Shridhar2602 👍🏽

**Pull request merged**
