### PR TITLE
Issues 1 and 4 solved

### PR DESCRIPTION
**Pull request by GSri30**

### CODE REVIEW

**Review by kernelpanic77 — CHANGES_REQUESTED** [review]
@GSri30 Looks good. 

1. PLs, add LinkedIn Logo and URL also.
2. Also add zense png avatar for zense author.

That's all.

**Comment by GaganAgarwal77** [comment]
@GSri30 This does not fix the triangle issue, now the entire post comes in zoomed into the 2nd page, we don't want any part of the clicked photo to come to the 2nd page.

**Comment by GSri30** [comment]
@GaganAgarwal77 Oh so the issue is there shouldn't be any triangle animation and also the specific card background should be the same for everything?

**Comment by GaganAgarwal77** [comment]
> @GaganAgarwal77 Oh so the issue is there shouldn't be any triangle animation and also the specific card background should be the same for everything?

Yes

**Pull request merged**
